<a href="https://colab.research.google.com/github/ilham115/Analisis-Data-12231950/blob/main/Tugas_A_M_Ilham_12239150.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
url_yk = "https://raw.githubusercontent.com/rahmadsa/dataset/main/transaksi_ritel_yk.csv"
url_mgl = "https://raw.githubusercontent.com/rahmadsa/dataset/main/transaksi_ritel_mgl.csv"

df_yk = pd.read_csv(url_yk)
df_mgl = pd.read_csv(url_mgl)

print(df_yk.head())

      tanggal     kode                   nama  jumlah    harga area
0  10-04-2020  Item-11      Sabun Cuci Piring     3.0  14000.0   YK
1  10-04-2020  Item-11      Sabun Cuci Piring     3.0  14000.0   YK
2  10-04-2020  Item-11      Sabun Cuci Piring     2.0  14000.0   YK
3  10-04-2020  Item-03  Gula Pasir Putih 1 kg     2.0  12500.0   YK
4  10-04-2020  Item-11      Sabun Cuci Piring     3.0  14000.0   YK

In [3]:
df = pd.concat([df_yk, df_mgl], ignore_index=True)

print("Jumlah baris:", len(df))
print("Jumlah kolom:", len(df.columns))

Jumlah baris: 23849
Jumlah kolom: 6

In [4]:
df['harga'].describe()

count    23743.000000
mean     13319.197237
std      12099.236378
min       1000.000000
25%       5200.000000
50%      12000.000000
75%      15000.000000
max      63000.000000
Name: harga, dtype: float64

In [5]:
Q1 = df['harga'].quantile(0.25)
Q3 = df['harga'].quantile(0.75)

IQR = Q3 - Q1

batas_bawah = Q1 - (1.5 * IQR)
batas_atas = Q3 + (1.5 * IQR)

print("Batas bawah :", batas_bawah)
print("Batas atas :", batas_atas)

Batas bawah : -9500.0
Batas atas : 29700.0

In [6]:
outlier = df[
    (df['harga'] < batas_bawah) |
    (df['harga'] > batas_atas)
]

print("Jumlah outlier:", len(outlier))

Jumlah outlier: 2394

In [7]:
df_no_outlier = df[
    (df['harga'] >= batas_bawah) &
    (df['harga'] <= batas_atas)
]

print("Jumlah data sebelum hapus outlier :", len(df))
print("Jumlah data sesudah hapus outlier :", len(df_no_outlier))

Jumlah data sebelum hapus outlier : 23849
Jumlah data sesudah hapus outlier : 21349

In [8]:
df_no_outlier.isnull().sum()

tanggal    4
kode       5
nama       4
jumlah     5
harga      0
area       0
dtype: int64

In [9]:
df_no_outlier.duplicated().sum()

np.int64(6842)

In [10]:
df_dedup = df_no_outlier.drop_duplicates()

print("Jumlah data sebelum deduplikasi :", len(df_no_outlier))
print("Jumlah data sesudah deduplikasi :", len(df_dedup))

Jumlah data sebelum deduplikasi : 21349
Jumlah data sesudah deduplikasi : 14507